# Change these first
owner: coozila # Your GitHub organization or username, where this repository lives
repo: search-instances-uptime # The name of this repository
sites:
  - name: search.coozila.com
    url: https://search.coozila.com
  - name: www.coozila.com
    url: https://www.coozila.com
  - name: www.coozila.co.uk
    url: https://www.coozila.co.uk
  - name: uptime.coozila.com
    url: https://www.coozila.com
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.coozila.com
  #baseUrl: /search-instances-uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Coozila and Search instances
  introTitle: "Uptime of Coozila and Search instances"
  introMessage: This status page monitors [Coozila and Search instances](https://github.com/coozila/search-instances) for uptime.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
