# Change these first
owner: searxng # Your GitHub organization or username, where this repository lives
repo: searx-instances-uptime # The name of this repository
sites:
  - name: searx.space
    url: https://searx.space
  - name: baresearch.org
    url: https://baresearch.org
  - name: coppedge.info
    url: https://coppedge.info
  - name: darmarit.org
    url: https://darmarit.org/searx
  - name: dynabyte.ca
    url: https://dynabyte.ca
  - name: etsi.me
    url: https://etsi.me
  - name: freesearch.club
    url: https://freesearch.club
  - name: myprivatesrx.us
    url: https://myprivatesrx.us
  - name: northboot.xyz
    url: https://northboot.xyz
  - name: notsearch.uk
    url: https://notsearch.uk
  - name: ooglester.com
    url: https://ooglester.com
  - name: opnxng.com
    url: https://opnxng.com
  - name: paulgo.io
    url: https://paulgo.io
  - name: priv.au
    url: https://priv.au
  - name: privatus.live
    url: https://privatus.live
  - name: s.frlt.one
    url: https://s.frlt.one
  - name: s.trung.fun
    url: https://s.trung.fun
  - name: s.zhaocloud.net
    url: https://s.zhaocloud.net
  - name: search.0xgingi.com
    url: https://search.0xgingi.com
  - name: search.affusio.com
    url: https://search.affusio.com
  - name: search.berryez.xyz
    url: https://search.berryez.xyz
  - name: search.bus-hit.me
    url: https://search.bus-hit.me
  - name: search.charleseroop.com
    url: https://search.charleseroop.com
  - name: search.chemicals-in-the-water.eu
    url: https://search.chemicals-in-the-water.eu
  - name: search.cronobox.one
    url: https://search.cronobox.one
  - name: search.disroot.org
    url: https://search.disroot.org
  - name: search.dojoro.de
    url: https://search.dojoro.de
  - name: search.gcomm.ch
    url: https://search.gcomm.ch
  - name: search.kiwitalk.de
    url: https://search.kiwitalk.de
  - name: search.leptons.xyz
    url: https://search.leptons.xyz
  - name: search.listi.me
    url: https://search.listi.me
  - name: search.mdosch.de
    url: https://search.mdosch.de
  - name: search.neet.works
    url: https://search.neet.works
  - name: search.ononoki.org
    url: https://search.ononoki.org
  - name: search.opensrc.one
    url: https://search.opensrc.one
  - name: search.privacyguides.net
    url: https://search.privacyguides.net
  - name: search.rabbit-company.com
    url: https://search.rabbit-company.com
  - name: search.rhscz.eu
    url: https://search.rhscz.eu
  - name: search.rowie.at
    url: https://search.rowie.at
  - name: search.sapti.me
    url: https://search.sapti.me
  - name: search.serginho.dev
    url: https://search.serginho.dev
  - name: search.shininglea.dev
    url: https://search.shininglea.dev
  - name: search.smnz.de
    url: https://search.smnz.de
  - name: search.stinpriza.org
    url: https://search.stinpriza.org
  - name: search.suenram.us
    url: https://search.suenram.us
  - name: search.trom.tf
    url: https://search.trom.tf
  - name: search.us.projectsegfau.lt
    url: https://search.us.projectsegfau.lt
  - name: search.zzls.xyz
    url: https://search.zzls.xyz
  - name: searx.baczek.me
    url: https://searx.baczek.me
  - name: searx.be
    url: https://searx.be
  - name: searx.becomesovran.com
    url: https://searx.becomesovran.com
  - name: searx.bissisoft.com
    url: https://searx.bissisoft.com
  - name: searx.catfluori.de
    url: https://searx.catfluori.de
  - name: searx.chocoflan.net
    url: https://searx.chocoflan.net
  - name: searx.cthd.icu
    url: https://searx.cthd.icu
  - name: searx.delicta.pp.ua
    url: https://searx.delicta.pp.ua
  - name: searx.divided-by-zero.eu
    url: https://searx.divided-by-zero.eu
  - name: searx.dresden.network
    url: https://searx.dresden.network
  - name: searx.ericaftereric.top
    url: https://searx.ericaftereric.top
  - name: searx.esmailelbob.xyz
    url: https://searx.esmailelbob.xyz
  - name: searx.fmac.xyz
    url: https://searx.fmac.xyz
  - name: searx.fossencdi.org
    url: https://searx.fossencdi.org
  - name: searx.gnous.eu
    url: https://searx.gnous.eu
  - name: searx.gnu.style
    url: https://searx.gnu.style
  - name: searx.juancord.xyz
    url: https://searx.juancord.xyz
  - name: searx.kutay.dev
    url: https://searx.kutay.dev
  - name: searx.mastodontech.de
    url: https://searx.mastodontech.de
  - name: searx.mha.fi
    url: https://searx.mha.fi
  - name: searx.mxchange.org
    url: https://searx.mxchange.org
  - name: searx.namejeff.xyz
    url: https://searx.namejeff.xyz
  - name: searx.netzspielplatz.de
    url: https://searx.netzspielplatz.de
  - name: searx.nixnet.services
    url: https://searx.nixnet.services
  - name: searx.oakleycord.dev
    url: https://searx.oakleycord.dev
  - name: searx.orion-hub.fr
    url: https://searx.orion-hub.fr
  - name: searx.prvcy.eu
    url: https://searx.prvcy.eu
  - name: searx.rasp.fr
    url: https://searx.rasp.fr
  - name: searx.roflcopter.fr
    url: https://searx.roflcopter.fr
  - name: searx.ru
    url: https://searx.ru
  - name: searx.semipvt.com
    url: https://searx.semipvt.com
  - name: searx.sev.monster
    url: https://searx.sev.monster
  - name: searx.si
    url: https://searx.si
  - name: searx.sp-codes.de
    url: https://searx.sp-codes.de
  - name: searx.thefloatinglab.world
    url: https://searx.thefloatinglab.world
  - name: searx.tiekoetter.com
    url: https://searx.tiekoetter.com
  - name: searx.tuxcloud.net
    url: https://searx.tuxcloud.net
  - name: searx.tyil.nl
    url: https://searx.tyil.nl
  - name: searx.webheberg.info
    url: https://searx.webheberg.info
  - name: searx.work
    url: https://searx.work
  - name: searx.xyz
    url: https://searx.xyz
  - name: searx.zapashcanon.fr
    url: https://searx.zapashcanon.fr
  - name: searxng.au
    url: https://searxng.au
  - name: searxng.bandarawela.net
    url: https://searxng.bandarawela.net
  - name: searxng.diadz.de
    url: https://searxng.diadz.de
  - name: searxng.nicfab.eu
    url: https://searxng.nicfab.eu
  - name: spot.murena.io
    url: https://spot.murena.io
  - name: srx.cosmohub.io
    url: https://srx.cosmohub.io
  - name: stalk.antelope.day
    url: https://stalk.antelope.day
  - name: suche.tromdienste.de
    url: https://suche.tromdienste.de
  - name: swag.pw
    url: https://swag.pw
  - name: sx.catgirl.cloud
    url: https://sx.catgirl.cloud
  - name: www.gruble.de
    url: https://www.gruble.de
  - name: www.jabber-germany.de
    url: https://www.jabber-germany.de/searx
  - name: xo.wtf
    url: https://xo.wtf
  - name: searx.neocities.org
    url: https://searx.neocities.org
  - name: search.projectsegfau.lt
    url: https://search.projectsegfau.lt
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.searxng.org
  #baseUrl: /searx-instances-uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: SearXNG and SearX instances
  introTitle: "Uptime of SearXNG and SearX instances"
  introMessage: This status page monitors [SearXNG and SearX instances](https://github.com/searxng/searx-instances) for uptime.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
